<?php
/*
 * Your installation or use of this SugarCRM file is subject to the applicable
 * terms available at
 * http://support.sugarcrm.com/Resources/Master_Subscription_Agreements/.
 * If you do not agree to all of the applicable terms or do not have the
 * authority to bind the entity as an authorized representative, then do not
 * install or use this SugarCRM file.
 *
 * Copyright (C) SugarCRM Inc. All rights reserved.
 */

// THIS CONTENT IS GENERATED BY MBPackage.php
$manifest = array (
  //~ 'built_in_version' => '7.9.0.0',
  'acceptable_sugar_versions' => 
  array (
    0 => '7.9.*',
  ),
  'acceptable_sugar_flavors' => 
  array (
    0 => 'ENT',
    1 => 'ULT',
  ),
  'readme' => '',
  'key' => 'hats',
  'author' => 'Hatim Alam',
  'description' => 'This package contains module to copy one user dashboards to other user(s) easily via selection list.',
  'icon' => '',
  'is_uninstallable' => true,
  'name' => 'Copy User Dashboards',
  'published_date' => '2017-08-24 18:15:00',
  'type' => 'module',
  'version' => '1.0',
  'remove_tables' => 'prompt',
);


$installdefs = array (
  'id' => 'CopyDashboard',
  'beans' => 
  array (
    0 => 
    array (
      'module' => 'hats_DashboardTemplate',
      'class' => 'hats_DashboardTemplate',
      'path' => 'modules/hats_DashboardTemplate/hats_DashboardTemplate.php',
      'tab' => false,
    ),
  ),
  'copy' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/modules/hats_DashboardTemplate',
      'to' => 'modules/hats_DashboardTemplate',
    ),
    1 =>
    array (
      'from' => '<basepath>/SugarModules/custom/relationships/relationships/hats_dashboardtemplate_usersMetaData.php',
      'to' => 'custom/metadata/hats_dashboardtemplate_usersMetaData.php',
    ),
    2 =>
    array (
      'from' => '<basepath>/SugarModules/custom/relationships/vardefs/hats_dashboardtemplate_users_hats_DashboardTemplate.php',
      'to' => 'custom/Extension/modules/hats_DashboardTemplate/Ext/Vardefs/hats_dashboardtemplate_users_hats_DashboardTemplate.php',
    ),
    3 =>
    array (
      'from' => '<basepath>/SugarModules/custom/relationships/vardefs/hats_dashboardtemplate_users_Users.php',
      'to' => 'custom/Extension/modules/Users/Ext/Vardefs/hats_dashboardtemplate_users_Users.php',
    ),
    4 =>
    array (
      'from' => '<basepath>/SugarModules/custom/modules/hats_DashboardTemplate/clients',
      'to' => 'custom/modules/hats_DashboardTemplate/clients',
    ),
    5 =>
    array (
      'from' => '<basepath>/SugarModules/custom/modules/hats_DashboardTemplate/Ext',
      'to' => 'custom/Extension/modules/hats_DashboardTemplate/Ext',
    ),
    6 =>
    array (
      'from' => '<basepath>/SugarModules/custom/modules/Administration/Ext',
      'to' => 'custom/Extension/modules/Administration/Ext',
    ),
  ),
  'language' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/language/application/en_us.lang.php',
      'to_module' => 'application',
      'language' => 'en_us',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/language/application/en_us.sugar_dashboard_module_list_dom.php',
      'to_module' => 'application',
      'language' => 'en_us',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/language/application/en_us.sugar_dashboard_view_name_dom.php',
      'to_module' => 'application',
      'language' => 'en_us',
    ),
  ),
  'image_dir' => '<basepath>/icons',
);
